<?php
// $Id$

/**
* Implement hook_taxon_formatter_types.
* Creates a formatter for tvk content fields that can output an OpenLayers map with NBN species data overlay.
*/
function nbn_dynamic_map_taxon_formatter_types() {
  $formatter = array(
    'nbn_dynamic_map' => array(
      'title' => t('NBN Dynamic Map'),
      // field type is tvk, tlick or brc (+GBIF?)
      'field_type' => 'tvk',
      // function that generates the form using Forms API, with arguments for the current settings values, type name (e.g. nbn_dynamic_map) and optional $args
      'form_callback' => 'nbn_dynamic_map_taxon_formatter_settings_form',
      'form_args' => array() // can be used to pass arguments to the form
    )
  );
  return $formatter;
}

/**
 * This defines the drupal form used for the settings of this formatter type.
 */
function nbn_dynamic_map_taxon_formatter_settings_form($settings, $type, $args) {
  if ($type=='nbn_dynamic_map') {
    // apply some defaults
    $settings = array_merge(array(
      'width' => 200,
      'height' => 300
    ), $settings);
    $form = array();
    // @todo validate width and height
    $form['width'] = array(
      '#type' => 'textfield',
      '#title' => t('Width (px)'),
      '#description' => t('Width of the map in pixels.'),
      '#required' => TRUE,
      '#default_value' => $settings['width']
    );
    $form['height'] = array(
      '#type' => 'textfield',
      '#title' => t('Height (px)'),
      '#description' => t('Height of the map in pixels.'),
      '#required' => TRUE,
      '#default_value' => $settings['height']
    );    
    $form['datasets'] = array(
      '#type' => 'textarea',
      '#title' => t('Datasets'),
      '#description' => t('List the keys of the datasets to restrict the query to one per line, or leave blank for no dataset filter.'),
      '#required' => FALSE,
      '#default_value' => $settings['datasets'],
      '#wysiwyg' => FALSE
    );
  }
  return $form;
}

/**
 * Implements the output theme function.
 * @todo Theming
 * @todo NBN map web service integration
 */
function theme_nbn_dynamic_map_taxon_formatter_output($element, $preset) {
  // return nothing if no TVK.
  $tvk = trim($element['#item']['safe_value']);
  if (empty($tvk))
    return '';
  iform_load_helpers(array('map_helper'));
  $r = map_helper::map_panel(array(
    'presetLayers' => array('google_physical'), /****/
    'editLayer' => false,
    'initial_lat'=>variable_get('indicia_map_centroid_lat', 55),
    'initial_long'=>variable_get('indicia_map_centroid_long', -1),
    'initial_zoom'=>variable_get('indicia_map_zoom', 5),
    'width'=>$preset['settings']['width'],
    'height'=>$preset['settings']['width'],
    'standardControls'=>array('layerSwitcher','panZoomBar'),
    'rememberPos'=>false
  ));
  if (!empty($preset['settings']['datasets'])) {
    $ds = str_replace("\r\n", "\n", $preset['settings']['datasets']);
    $ds = str_replace("\r", "\n", $ds);
    $ds=explode("\n", trim($ds));
    $datasets = '?datasets='.implode(',', $ds);
  } else 
    $datasets='';
  // Datasets get embedded straight in the URL rather than passed as a property, as OpenLayers capitalises it which the gateway then ignores.
  map_helper::$javascript .= '
mapSettingsHooks.push(function(opts) {
  var nbn10 = new OpenLayers.Layer.WMS("NBN Gateway 10km data", "http://gis.nbn.org.uk/arcgis/rest/services/grids/SingleSpeciesMap/'.$tvk.'/WMSServer'.$datasets.'", 
      {LAYERS: "3", CRS:"EPSG:3857", VERSION:"1.3.0", FORMAT:"png", TRANSPARENT: true}, {isBaseLayer: false, opacity: 0.5, minResolution: 360}),
      nbn1 = new OpenLayers.Layer.WMS("NBN Gateway 1km data", "http://gis.nbn.org.uk/arcgis/rest/services/grids/SingleSpeciesMap/'.$tvk.'/WMSServer'.$datasets.'", 
      {LAYERS: "1", CRS:"EPSG:3857", VERSION:"1.3.0", FORMAT:"png", TRANSPARENT: true}, {isBaseLayer: false, opacity: 0.5, maxResolution: 361});  
  opts.layers.splice(0, 0, nbn10, nbn1);
});
';
  $r = theme('nbn_dynamic_map_output', $r, $preset);
  handle_resources();
  return $r;
}

/**
 * Theme function to wrap the dynamic map output in NBN Gateway terms and conditions.
 */
function theme_nbn_dynamic_map_output($map, $preset) {
  $result = '<div style="width: '.$preset['settings']['width'].'px; margin: 0 auto;">';
  $result .= $map;
  $result .= '<table width="100%">'.
      '<tbody><tr><td align="left"><a href="http://data.nbn.org.uk/help/popups/generalTerms.jsp">'.
      t('Gateway terms and conditions').'</a></td><td align="right"><a href="http://data.nbn.org.uk">'.
      '<img src="http://data.nbn.org.uk/images/NBNPower.gif" alt="NBN Logo" width="100" height="14"></a></td></tr></tbody></table></div>';
  return $result;  
}

/**
 * Implementation of hook_theme.
 */
function nbn_dynamic_map_theme() {
  $theme = array();
  $theme["nbn_dynamic_map_taxon_formatter_output"] = array(
      'arguments' => array('element' => NULL),
  );
  $theme["nbn_dynamic_map_output"] = array(
      'arguments' => array('element' => NULL),
  );
  return $theme;
}