<?php

include_once('species_accounts.features.inc');

function species_accounts_imagecache_default_presets() {
  $presets = array();
  $presets['thumbnail'] = array (
    'presetname' => 'thumbnail',
    'actions' =>
    array (
      0 =>
      array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' =>
        array (
          'height' => '100',
        ),
      ),
    ),
  );

  $presets['medium'] = array (
    'presetname' => 'medium',
    'actions' =>
    array (
      0 =>
      array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' =>
        array (
          'height' => '400',
        ),
      ),
    ),
  );
  
  $presets['large'] = array (
    'presetname' => 'large',
    'actions' =>
    array (
      0 =>
      array (
        'weight' => '0',
        'module' => 'imagecache',
        'action' => 'imagecache_scale',
        'data' =>
        array (
          'height' => '1000',
        ),
      ),
    ),
  );

  return $presets;
}
