<?php

/**
 * Uninstall method cleans up the variables we may have created.  
 */
function indicia_quickstart_uninstall() {
  variable_del('iform_master_checklist_id');
  // These variables are not used anymore, but may have been created by an earlier version of the quickstart module.
  variable_del('iform_param_certainattr');
  variable_del('iform_param_maxcertain');
  variable_del('iform_param_mincertain');
}
