<?php

/**
 * @file
 * Iform Mobile Module's Drupal functionality.
 */

/**
 *  Implements hook_menu().
 */
function iform_mobile_menu()
{
    $items = array();

    // Mobile registration-based actions
    $items['mobile/log'] = array(
        'title'             => 'Accepts an app request to log data.',
        'page callback'     => 'iform_mobile_log',
        'access callback'   => true,
    );

    return $items;
}

/**
 * Logs app send data. Uses JSON format.
 * todo: add authentication option.
 */
function iform_mobile_log(){
    //get json
    $data = json_decode(file_get_contents('php://input'), true);

    //if crawler visit exit
    if (empty($data)){
        drupal_add_http_header('Status', '400 Bad Request');
        print 'Bad request';
    }

    iform_mobile_auth_log(file_get_contents('php://input'));

    return print_r($data);
}

/**
 * Implements hook_library().
 */
function iform_mobile_library() {
  $path = drupal_get_path('module', 'iform_mobile');

  $libraries = array();
  $libraries['main'] = array(
    'title' => 'iForm Mobile',
    'js' => array(
      $path . '/libs/IndexedDBShim.js' => array(),
      $path . '/libs/fastclick.js' => array(),
      $path . '/libs/latlon/vector3d.js' => array(),
      $path . '/libs/latlon/geo.js' => array(),
      $path . '/libs/latlon/latlon-ellipsoid.js' => array(),
      $path . '/libs/latlon/osgridref.js' => array(),
      $path . '/libs/photoswipe-3.0.4/klass.min.js' => array(),
      $path . '/libs/photoswipe-3.0.4/code.photoswipe.jquery-3.0.4.min.js' => array(),
      $path . '/libs/handlebars.js' => array(),
      $path . '/dist/iform-mobile.js' => array(),
    ),
    'css' => array(
      $path . '/libs/photoswipe-3.0.4/photoswipe.css' => array(),
    ),
  );

  return $libraries;
}