<?php

/**
 * @file
 * Iform Mobile Module's Drupal functionality.
 */

/**
 * Implements hook_library().
 */
function iform_mobile_library() {
  $path = drupal_get_path('module', 'iform_mobile');

  $libraries = array();
  $libraries['main'] = array(
    'title' => 'iForm Mobile',
    'version' => '1.0',
    'js' => array(
      $path . '/libs/IndexedDBShim.js' => array(),
      $path . '/libs/fastclick.js' => array(),
      $path . '/libs/latlon/vector3d.js' => array(),
      $path . '/libs/latlon/geo.js' => array(),
      $path . '/libs/latlon/latlon-ellipsoid.js' => array(),
      $path . '/libs/latlon/osgridref.js' => array(),
      $path . '/libs/photoswipe-3.0.4/klass.min.js' => array(),
      $path . '/libs/photoswipe-3.0.4/code.photoswipe.jquery-3.0.4.min.js' => array(),
      $path . '/libs/handlebars.js' => array(),
      $path . '/libs/jquery.validate.js' => array(),
      $path . '/dist/iform-mobile.js' => array(),
    ),
    'css' => array(
      $path . '/libs/photoswipe-3.0.4/photoswipe.css' => array(),
    ),
  );

  return $libraries;
}