<?php

/**
 * @file
 * Iform Mobile Module's Drupal functionality.
 */

/**
 * Implements hook_library().
 */
function iform_mobile_library() {
  $path = drupal_get_path('module', 'iform_mobile');

  $libraries = array();
  $libraries['main'] = array(
    'title' => 'iForm Mobile',
    'js' => array(
      $path . '/js/dist/iform-mobile.libs.js' => array(),
      $path . '/js/dist/iform-mobile.js' => array(),
    ),
    'css' => array(
      $path . '/js/src/lib/photoswipe/photoswipe.css' => array(),
    ),
  );

  return $libraries;
}