<?php defined('SYSPATH') or die('No direct script access.');

class New_Password_Controller extends Indicia_Controller {

	public function index()
	{
		if ( ! empty($_SESSION['auth_user']) AND is_object($_SESSION['auth_user'])
			AND ($_SESSION['auth_user'] instanceof User_Model) AND $_SESSION['auth_user']->loaded)
		{
			// Everything is okay so far
			$user = new User_Model($_SESSION['auth_user']->id);
			$person = ORM::factory('person', $user->person_id);	
			$view = new View('login/new_password');
			$view->model = $user;
			$view->username = $user->username; // as is disabled doesn't make it through to post, so unavailable in model post validation failure.
			$view->email_address = $person->email_address;
			$this->template->title = 'Enter New Password';
			$this->template->content = $view;
		} else {
			$this->template->title = 'New Password Invocation Error';
			$this->template->content = new View('login/login_message');	
			$this->template->content->message = 'You cannot set your password without being logged in.<br />';
		}
	}

	/*
	 * The email function is called from the link sent out on the forgotten password
	 */
	public function email()
	{
		if ($this->uri->total_arguments()==0)
		{
			$this->template->title = 'New Password Invocation Error';
			$this->template->content = new View('login/login_message');	
			$this->template->content->message = 'You cannot set your password from an email without an associated ID string.<br />';
			return;
		}

		$user = new User_Model(array('forgotten_password_key' => $this->uri->argument(1)));
		if ( ! $user->loaded )
		{
			$this->template->title = 'New Password Invocation Error';
			$this->template->content = new View('login/login_message');	
			$this->template->content->message = 'The identification string embedded in this link is invalid.<br /><br />If this link has been followed from an email generated by this system, then the most likely causes of the error are (1) that this link has already been used to alter the password, (2) there has been a successful login since this email was sent.<br /><br />These links a single use only, and once they have been used the identification string is invalidated.<br /><br />If you wish to reset your password, please request another Forgotten Password email. <a href="'.url::site().'forgotten_password">Click here to request an email allowing you to reset your password</a>.';
			return;
		}

		
		$person = ORM::factory('person', $user->person_id);	
		$view = new View('login/new_password');
		$view->model = $user;
		$view->username = $user->username; // as is disabled doesn't make it through to post, so unavailable in model post validation failure.
		$view->email_address = $person->email_address;
		$view->key = $this->uri->argument(1);
		$this->template->title = 'Enter New Password';
		$this->template->content = $view;
		
	}
	
	public function save() {
		$user = new User_Model($_POST['id']);
		$username = $user->username;
		$password = $_POST['password'];
		$person = ORM::factory('person', $user->person_id);
		
		$_POST = new Validation($_POST);
		if ($user->password_validate($_POST, TRUE)) {
			
			// with the password updated, login and jump to the home page
			$this->auth->login($user->id, $password);
			url::redirect('');
			
		} else {
	 		// errors are now embedded in the model
			$view = new View('login/new_password');
			$view->model = $user;
			$view->username = $username;
			$view->email_address = $person->email_address;
			$view->key = $user->key;
			$this->template->title = 'Enter New Password';
			$this->template->content = $view;
	 		
		}
	}
}